version: "3"
services:
  redis:
    image: redis:alpine3.13
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
    - $PWD/redis/redis-data:/var/lib/redis
    - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master